{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "Notification.serviceAccountName" . }}
  labels:
{{ include "Notification.labels" . | nindent 4 }}
{{- end -}}
